name: Greet Death
favicon: null
layout_spectrum: 0.25865
typography_spectrum: 0.47469
title: 'If you see no reason for giving thanks, the fault lies only in yourself'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ebd59c'
    - '#c49245'
    - '#aa7127'
    - '#42382c'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
