name: null
favicon: null
layout_spectrum: 0.7359663683455437
typography_spectrum: 0.2735864103306085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5001110814046115
  lightness: 0.9583522768225521
  saturation: 0.921527111902833
  rhythmicContrast: 0.8291073117870837
purpose: []
